# Generated by Django 6.0.1 on 2026-02-02 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('pain', 'Обезболивающие'), ('cold', 'От простуды'), ('allergy', 'От аллергии'), ('vitamins', 'Витамины'), ('digestive', 'Для пищеварения'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('icon', models.CharField(default='fas fa-pills', max_length=50, verbose_name='Иконка Font Awesome')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фотографию товара', null=True, upload_to='products/', verbose_name='Фотография товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер консультации')),
                ('consultation_type', models.CharField(choices=[('general', 'Общая консультация терапевта'), ('pediatric', 'Консультация педиатра'), ('cardiology', 'Консультация кардиолога'), ('neurology', 'Консультация невролога'), ('dermatology', 'Консультация дерматолога'), ('second_opinion', 'Второе мнение'), ('gastroenterology', 'Консультация гастроэнтеролога'), ('endocrinology', 'Консультация эндокринолога')], max_length=50, verbose_name='Тип консультации')),
                ('consultation_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('appointment_date', models.DateField(verbose_name='Дата приема')),
                ('appointment_time', models.TimeField(verbose_name='Время приема')),
                ('patient_name', models.CharField(max_length=200, verbose_name='ФИО пациента')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('symptoms', models.TextField(verbose_name='Симптомы')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('examinations', models.TextField(blank=True, verbose_name='Направления на обследования')),
                ('next_appointment', models.DateField(blank=True, null=True, verbose_name='Следующий прием')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('confirmed', 'Подтверждена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultation_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.consultation')),
            ],
            options={
                'verbose_name': 'Документ консультации',
                'verbose_name_plural': 'Документы консультаций',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('therapist', 'Терапевт'), ('pediatrician', 'Педиатр'), ('cardiologist', 'Кардиолог'), ('neurologist', 'Невролог'), ('dermatologist', 'Дерматолог'), ('gastroenterologist', 'Гастроэнтеролог'), ('endocrinologist', 'Эндокринолог'), ('surgeon', 'Хирург'), ('other', 'Другой специалист')], max_length=50, verbose_name='Специальность')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('description', models.TextField(blank=True, verbose_name='О враче')),
                ('price', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Стоимость консультации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Рабочие часы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hospital', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['specialty', 'user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_consultations', to='main.doctorprofile'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_consultations', to='main.hospital'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('fullname', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('pharmacy', models.CharField(blank=True, max_length=200, verbose_name='Аптека')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(max_length=50, verbose_name='Время доставки')),
                ('payment_method', models.CharField(choices=[('card', 'Картой онлайн'), ('cash', 'Наличными'), ('card_on_delivery', 'Картой при получении')], max_length=20, verbose_name='Способ оплаты')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала приема')),
                ('end_time', models.TimeField(verbose_name='Время окончания приема')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('max_patients', models.IntegerField(default=10, verbose_name='Максимум пациентов')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.doctorprofile')),
            ],
            options={
                'verbose_name': 'Расписание врача',
                'verbose_name_plural': 'Расписания врачей',
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='DoctorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронирован')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='main.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='main.doctorprofile')),
            ],
            options={
                'verbose_name': 'Временной слот врача',
                'verbose_name_plural': 'Временные слоты врачей',
                'ordering': ['date', 'start_time'],
                'unique_together': {('doctor', 'date', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['user', 'status'], name='main_consul_user_id_5081f4_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['doctor', 'appointment_date', 'appointment_time'], name='main_consul_doctor__576567_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['consultation_number'], name='main_consul_consult_6077f9_idx'),
        ),
    ]
