# Generated by Django 6.0.1 on 2026-02-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('work', 'Справка для работы'), ('study', 'Справка для учебы'), ('sick_leave', 'Больничный/нетрудоспособность'), ('sports', 'Справка для спорта'), ('other', 'Другая')], max_length=30, verbose_name='Тип справки')),
                ('reason', models.TextField(verbose_name='Причина/описание запроса')),
                ('doctor_comment', models.TextField(blank=True, verbose_name='Комментарий врача')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('review', 'На рассмотрении'), ('issued', 'Выдано'), ('rejected', 'Отказано')], default='new', max_length=20, verbose_name='Статус')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/', verbose_name='PDF справки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдано')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='main.consultation', verbose_name='Консультация')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='main.doctorprofile', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинская справка',
                'verbose_name_plural': 'Медицинские справки',
                'ordering': ['-created_at'],
            },
        ),
    ]
